esphome:
  name: doorbell
  friendly_name: Doorbell

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

psram:
  mode: octal
  speed: 80MHz

packages:
  core: !include debug.yaml

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret "home_assistant_api_key"

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

web_server:
  
i2s_audio:
  i2s_lrclk_pin: GPIO07
  i2s_bclk_pin: GPIO08

speaker:
  - platform: i2s_audio
    id: i2s_speaker
    dac_type: external
    i2s_dout_pin: GPIO09
    sample_rate: 48000
    channel: mono
  - platform: mixer
    output_speaker: i2s_speaker
    source_speakers:
      - id: announcement_mixer_speaker
      - id: media_mixer_speaker
  - platform: resampler
    id: announcement_speaker
    output_speaker: announcement_mixer_speaker
  - platform: resampler
    id: media_speaker
    output_speaker: media_mixer_speaker

media_player:
  - platform: speaker
    name: "Doorbell Speaker"
    task_stack_in_psram: true
    media_pipeline:
      speaker: media_speaker
    announcement_pipeline:
      speaker: announcement_speaker
    files:
      - id: front_door_sound
        file: front_door.flac

button:
  - platform: template
    name: "Play Doorbell"
    icon: mdi:bell
    on_press:
      - logger.log: "Playing doorbell"
      - media_player.speaker.play_on_device_media_file:
          media_file: front_door_sound
          announcement: true
